apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/test-rhtap-71-tenant/load-app-1a2a33d5-431f-48bd-9952-fe7b66b81fa8/devfile-sample@sha256:c1620b39ed56cc9389cef4d2c08799ee19442db26e357c5ad4baf03e1ad17767
        name: my-nodejs
        resources: {}
status: {}
